### ISSUE TITLE
Metadata timestamp in shadow delta

### ISSUE THREAD

**Issue by pablocastilla** [seqsense/aws-iot-device-sdk-go#211]
Hi!

It would be fantastic to have the shadow metadata timestamps available in the delta event, I need to discard changes if they are too old.

Thanks for this library.

**Comment by at-wat** [comment]
Hi, @pablocastilla
You can get timestamp of the delta event by `Shadow.Document().Timestamp`.
As the callback function set by `Shadow.OnDelta()` is called synchronously by default, Thing Document returned by `Shadow.Document()` in OnDelta callback should be guaranteed to be the version given by the delta event. (unless wrapping the handler by `mqtt.ServeAsync`)
Could you try this way?

**Comment by pablocastilla** [comment]
the problem is that I would need to access the property timestamp because I need to discard the changes I received if a defined time has passed. Also, I don't know why, the shadow timestamp is different than the last property updated timestamp.

Anyhow what I have done is to write my own timestamp when I update a property.

**Comment by at-wat** [comment]
I had misread which timestamp.

So, `Metadata` field should be added to
https://github.com/seqsense/aws-iot-device-sdk-go/blob/736a443882c7b1d186aec10954e939d12ed824f7/shadow/state.go#L46-L50
https://github.com/seqsense/aws-iot-device-sdk-go/blob/736a443882c7b1d186aec10954e939d12ed824f7/shadow/state.go#L60-L65
https://github.com/seqsense/aws-iot-device-sdk-go/blob/736a443882c7b1d186aec10954e939d12ed824f7/shadow/state.go#L74-L78
and applied to the locally stored ThingDocument.

**Comment by at-wat** [comment]
Adding metadata support: #213

**Comment by at-wat** [comment]
Added by #213 and released as https://github.com/seqsense/aws-iot-device-sdk-go/releases/tag/v5.0.0-rc1
