### ISSUE TITLE
being able to handle topics and shadows with the same client

### ISSUE THREAD

**Issue by pablocastilla** [seqsense/aws-iot-device-sdk-go#220]
Hi,

I am trying to subscribe to shadow changes and to one topic with the same client and I think I am not able to do it. When I set the handler I have to do it or with shadows or with the message handler for the topic subscription. Am I wrong? If not I think it is an interesting feature.

Thanks

**Comment by at-wat** [comment]
It can be done by using `mqtt.ServeMux`. ([godoc](https://pkg.go.dev/github.com/at-wat/mqtt-go#ServeMux))
```go
var mux mqtt.ServeMux
cli.Handle(&mux)

s, _ := shadow.New(ctx, cli)
// Process all messages by shadow handler
// (Topic filter may be narrowed by passing "$aws/things/.../shadow/..." instead of "#")
mux.Handle("#", s)

// Process messages on topic/to/be/subscribed by callback()
mux.Handle("topic/to/be/subscribed", callback) 
```

The relation of `mqtt.Handler` and `mqtt.ServeMux` is similar to `net/http`'s `http.Handler` and `http.ServeMux`.

**Comment by at-wat** [comment]
Examples are updated to use `mqtt.ServeMux`.
